version: '3'
services:
  db-cats-api:
    image: postgres:16
    restart: always
    ports:
      - "5444:5432"
#    по дефолту postgres запускается на порту 5432
#    на нашем хосте это будет порт 5444
#    мы пробрасываем порт 5432 (из виртуальной машины) на 5444 (реальную)
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: cats-api