spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5444/cats-api
    driver-class-name: org.postgresql.Driver
    username: root
    password: root


  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    show-sql: true