apiVersion: apps/v1  # файл с конфигурациями
kind: Deployment  # тип сущности deployment
metadata:
  name: cats-api
  labels:
    app: cats-api # метка, за которую сможем зацепиться,
                  # когда будем работать с сервисами
spec:
  replicas: 3
  selector:
    matchLabels:      # по какой метке матчить
      app: cats-api
  template:         # параметры запуска приложения
    metadata:
      labels:
        app: cats-api  # с какой меткой запускать
    spec:             # конфиги котейнеров
      containers:
        - name: cats-api  # задаем имя контейнера
          image: vitalisin/cats-api:1.0.0  # наш image
          ports:
            - containerPort: 8080
          env:
            - name: DATASOURCE_HOST
              value: 192.168.100.27
            - name: spring.mvc.servlet.path
              value: /cats-api